use TV
--Грязное чтение READ COMMITTED (1)

UPDATE EMPLOYEE SET country_id = 2
WHERE EMPLOYEE.employee_id = 25

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION 
SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 25

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 25

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 25
COMMIT