use TV
--Неповторяющееся чтение READ COMMITTED (1)

UPDATE [EVENT] SET danger_id = 1
WHERE [EVENT].event_id = 4

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION 
SELECT * 
FROM [EVENT] 
WHERE [EVENT].event_id = 4

SELECT * 
FROM [EVENT] 
WHERE [EVENT].event_id = 4
COMMIT 