use TV
--Грязное чтение READ UNCOMMITTED (1)

UPDATE EMPLOYEE SET country_id = 2
WHERE EMPLOYEE.employee_id = 25

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION 
SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 25

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 25

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 25
COMMIT

--Грязное чтение READ UNCOMMITTED (2)

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION 
UPDATE EMPLOYEE
SET country_id = 1
WHERE EMPLOYEE.employee_id = 25
ROLLBACK

--Потерянные изменения READ UNCOMMITTED (1)

UPDATE REPORT SET [type_id] = 3
WHERE REPORT.report_id = 5

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION
UPDATE REPORT
SET [type_id] = 1
WHERE REPORT.report_id = 5
COMMIT

SELECT * FROM REPORT WHERE REPORT.report_id = 5

--Потерянные изменения READ UNCOMMITTED (2)

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION
UPDATE REPORT
SET [type_id] = 2
WHERE REPORT.report_id = 5
COMMIT