use TV
--Фантом SERIALIZABLE (1)

DELETE FROM [CONTRACT]
WHERE [CONTRACT].contract_id = 51

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION 

SELECT * 
FROM [CONTRACT]
WHERE [CONTRACT].hire_date > '01.08.2018'

SELECT * 
FROM [CONTRACT]
WHERE [CONTRACT].hire_date > '01.08.2018'
COMMIT

--Фантом SERIALIZABLE (2)

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION 

INSERT [CONTRACT](contract_id, employee_id, job_id, hire_date, department_id) VALUES(51, 50, 5, '25.09.2018', 10)
COMMIT